// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Asaph.Core.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("AddSongDirector", SourceFile="Features\\AddSongDirector.feature", SourceLine=0)]
    public partial class AddSongDirectorFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "AddSongDirector.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "AddSongDirector", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SomeoneTriesToAddASongDirector(string adderRank, string fullName, string emailAddress, string phoneNumber, string rankName, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("adderRank", adderRank);
            argumentsOfScenario.Add("fullName", fullName);
            argumentsOfScenario.Add("emailAddress", emailAddress);
            argumentsOfScenario.Add("phoneNumber", phoneNumber);
            argumentsOfScenario.Add("rankName", rankName);
            argumentsOfScenario.Add("message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Someone tries to add a song director", null, tagsOfScenario, argumentsOfScenario);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
 testRunner.Given(string.Format("the person trying to add a song director is a {0}", adderRank), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 5
 testRunner.And(string.Format("the new song director full name is {0}", fullName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 6
 testRunner.And(string.Format("the new song director email address is {0}", emailAddress), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 7
 testRunner.And(string.Format("the new song director phone number is {0}", phoneNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 8
 testRunner.And(string.Format("the new song director rank is {0}", rankName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.When("the song director add is handled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
 testRunner.Then(string.Format("the result message should be {0}", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 0", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant0()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "John Doe", "john.doe@gmail.com", "123-456-1234", "<null>", "John Doe was added.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 1", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant1()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "Jane Doe", "jane.doe@gmail.com", "987-654-9876", "Apprentice", "Jane Doe was added.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 2", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant2()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "Jane Doe", "jane.doe@gmail.com", "987-654-9876", "Journeyer", "Jane Doe was added.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 3", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant3()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "John Doe", "john.doe@gmail.com", "123-456-1234", "Master", "John Doe was added.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 4", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant4()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "Jane Doe", "jane.doe@gmail.com", "987-654-9876", "Grandmaster", "Jane Doe was added.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 5", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant5()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "John Doe", "john.doe@gmail.com", "<null>", "<null>", "John Doe was added.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 6", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant6()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "Jane Doe", "<null>", "987-654-9876", "<null>", "Email address is required.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 7", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant7()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "<null>", "john.doe@gmail.com", "123-456-1234", "<null>", "Full name is required.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 8", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant8()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "John Doe", "1234567890", "123-456-1234", "<null>", "Invalid email address.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 9", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant9()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "Jane Doe", "jane.doe@gmail.com", "987-654-987", "<null>", "Invalid phone number.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 10", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant10()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Grandmaster", "John Doe", "john.doe@gmail.com", "123-456-1234", "Associate", "Invalid rank.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 11", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant11()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Apprentice", "Jane Doe", "jane.doe@gmail.com", "987-654-9876", "Apprentice", "You don\'t have permission to add song directors.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 12", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant12()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Journeyer", "Jane Doe", "jane.doe@gmail.com", "987-654-9876", "Apprentice", "You don\'t have permission to add song directors.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Someone tries to add a song director, Variant 13", SourceLine=13)]
        public virtual void SomeoneTriesToAddASongDirector_Variant13()
        {
#line 3
this.SomeoneTriesToAddASongDirector("Master", "Jane Doe", "jane.doe@gmail.com", "987-654-9876", "Apprentice", "You don\'t have permission to add song directors.", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
